
@startuml

left to right direction

rectangle "Timmo" {

  (Organiser rendez-vous)

  Agence --> (Ajouter client)
  Agence --> (Modifier client)
  Agence --> (Organiser rendez-vous)

  rectangle "LogiVente"{
    (Ajouter bien) .right.> (Créer mandat) : include
    Agence --> (Modifier bien)
    Agence --> (Ajouter bien)
    (Créer mandat) .up.> (Organiser rendez-vous) : include
  }

  rectangle "LogiAchat"{
    Agence --> (Créer promesse de vente)
    Agence --> (Créer envie)
    (Créer promesse de vente) .up.> (Organiser rendez-vous) : include
    Agence --> (Signer promesse de vente)
  }

  rectangle "LogiPub"{
    Agence --> (Créer document)
  }

  rectangle "LogiStat"{
    Agence --> (Voir stats)
  }

}


@enduml
