
@startuml

package app {

  folder agence [

    +Agence()
    +Mandat()
    +Promesse()
    +Notaire()

  ]

  folder pub [

    +AnnoncePub()
    +TypePub()
    +TypeTexte()
    +TypeHtml()
    +TypeImg()
    +TypeVid()

  ]

  folder user [

    +Client()
    +Personne()
    +Entreprise()
    +Envie()

  ]

  folder immo [

    +BienImmo()
    +Terrain()
    +Maison()
    +Appartement()

  ]

  pub <.down. agence : <<import>>
  user <.down. agence : <<import>>
  immo <.down. agence : <<import>>

}

@enduml
