
@startuml

package user {

  class Personne {
    -String nom
    -String adresse
    -Int telephone
    -String email
  }

  class Entreprise {
    -String formeJuridique
    -Int numSiren
  }

  Entreprise --|> Personne

}

package agence {

  class Agence {
    -String nom
    -HashSet<Date, Personne> listeRdvVendeur
    +CreerMandat(Personne, Mandat) : void
    +CreerEnvie(Personne, Envie) : void
    +Contacter(Envie, Mandat) : void
    +PriseRdvVendeur(Personne, Date) : void
    +OrganiserVisite(Envie, Mandat, Date) : void
    +OrganiserVente(Envie, Mandat, Date) : void
    +SignerPromesse(Promesse) : void
  }

  Personne "*"<-- Agence

  class Envie {
    -String type
    -Double prix
    -String localisation
    -Double surfaceSol
    -Int nbPieces
  }

  class Mandat {
    -HashSet<Date, Personne> listeRdvVisite
    -Int prix
    -Date vente
    -Date debut
    -Date fin
  }

  Agence -->"*" Mandat
  Agence -->"*" Envie

  Envie -->"1" Personne : "acheteur"
  Mandat -->"1" Personne : "vendeur"

  class Promesse {
    -Double prixVerseVendeur
    -String adresseNotaire
    -Date vente
    -Double commissionAgence
    -Double fraisVente
  }

  Agence -->"*" Promesse
  Mandat "1"<-- Promesse : "mandat"
  Envie "1"<-- Promesse : "envie"

  class Notaire {
    +VerserArgent()
  }

  Notaire "1"<-- Promesse : "notaire"

}

package pub {

  class AnnoncePub {
    -TypePub[] listePub
  }

  Agence -->"*" AnnoncePub

  abstract class TypePub {
    +addElem() : void
  }

  TypePub --> AnnoncePub

  class TypeTexte {
    +addElem() : void
  }

  class TypeHtml {
    +addElem() : void
  }

  class TypeImg {
    +addElem() : void
  }

  class TypeVid {
    +addElem() : void
  }

  TypeTexte -up-|> TypePub
  TypeHtml -up-|> TypePub
  TypeImg -up-|> TypePub
  TypeVid -up-|> TypePub

}

package immo {

  abstract class BienImmo {
    -Int num
    -String adresse
    -String orientation
    -Double prix
    -Date vente
    -Date[] dispo
    +Correspondance(Envie) : Double
  }

  class Terrain {
    -Double surfaceSol
    -Double longueurFacade
  }

  class Maison {
    -Double surfaceHabitable
    -Int nbPieces
    -Int nbEtages
    -String chauffage
  }

  class Appartement {
    -Int nbPieces
    -Int etage
    -Double chargesMensuelles
  }

  BienImmo "1"<-- Mandat : "bienImmo"

  Terrain -up-|> BienImmo
  Maison -up-|> Terrain
  Appartement -up-|> BienImmo

}

@enduml
