
@startuml

hide footbox
title Footer removed

participant ":Agence" As A
participant ":Mandat" As M
participant ":Bien" As B
participant ":Envie" As E
participant ":Promesse" As Pro

A -> A : PriseRdvVendeur()
A -> A : CreerPersonne()

...

A -> A : CreerMandat()

@enduml
