
@startuml


participant ":Agence" As A
participant ":Personne" As Per
participant ":Mandat" As M
participant ":Bien" As B
participant ":Envie" As E
participant ":Promesse" As Pro
participant ":AnnoncePub" As AP
participant ":TypePub" As TP

A -> A : priseRdvVendeur()
A -> Per : creerPersonne()
Per --> A :
Per -> Per : SETTER Personne
A -> M : creerMandat()
M -> B : creerBien()
B --> M :
B -> B : SETTER Bien
M --> A :

...

B -> B : correspondance(Envie)

...

A -> E : creerEnvie()
E --> A :

...

A -> A : organiserVisite()

...

A -> A : organiserVente()
A -> Pro : creerPromesse()
Pro --> A :
Pro -> Pro : signerPromesse()

...

A -> A : voirStats()

...

A -> AP : creerDocument()
AP --> A :
AP -> TP : addElem()
TP --> AP :

@enduml
