
@startuml

package user {

  class Personne {
    -String nom
    -String adresse
    -Int telephone
    -String email
  }

  class Entreprise {
    -String formeJuridique
    -Int numSiren
  }

  Entreprise -up-|> Personne

  class Envie {
    -String type
    -Double prix
    -String localisation
    -Double surfaceSol
    -Int nbPieces
  }

  Personne *--"*" Envie : "listeEnvie"

}

package agence {

  class Agence {
    -String nom
    -HashSet<Date, Personne> listeRdvVendeur
    +creerPersonne(String, String, Int, String) : void
    +priseRdvVendeur(Personne, Date) : void
    +creerMandat(Personne, Mandat) : void
    +creerEnvie(Personne, Envie) : void
    +organiserVisite(Envie, Mandat, Date) : void
    +organiserVente(Envie, Mandat, Date) : void
    -creerPromesse(Promesse) : void
    +voirStats() : void
    +creerDocument() : void
  }

  Personne "*"-left-* Agence : "listePersonne"

  class Mandat {
    -HashSet<Date, Personne> listeRdvVisite
    -Int prix
    -Date vente
    -Date debut
    -Date fin
    -creerBien() : void
  }

  class Promesse {
    -Double prixVerseVendeur
    -String adresseNotaire
    -Date vente
    -Double commissionAgence
    -Double fraisVente
    +signerPromesse() : void
  }

  Agence *--"*" Mandat : "listeMandat"
  Agence *--"*" Promesse : "listePromesse"

  Mandat -->"1" Personne : "vendeur"
  Promesse -->"1" Personne : "acheteur"

  class Notaire {
    +verserArgent()
  }

  Agence *--"*" Notaire : "listeNotaire"

  Notaire "1"<-- Promesse : "notaire"

}

package pub {

  class AnnoncePub {
    +addElem(TypePub) : void
  }

  AnnoncePub "*"--* Agence : "listeAnnonce"
  TypePub "*"--* AnnoncePub : "listePub"

  abstract class TypePub {
    +getElem()
  }

  class TypeTexte {
    -String texte
    +getElem()
  }

  class TypeHtml {
    -String html
    +getElem()
  }

  class TypeImg {
    -String img
    +getElem()
  }

  class TypeVid {
    -String vid
    +getElem()
  }

  TypeTexte -up-|> TypePub
  TypeHtml -up-|> TypePub
  TypeImg -up-|> TypePub
  TypeVid -up-|> TypePub

}

package immo {

  abstract class BienImmo {
    -Int num
    -String adresse
    -String orientation
    -Double prix
    -Date vente
    -Date[] dispo
    +correspondance(Envie) : Double
  }

  BienImmo "*"-left-* Agence : "listeBien"
  Mandat -up->"1" BienImmo : "bien"
  Promesse -up->"1" BienImmo : "bien"

  class Terrain {
    -Double surfaceSol
    -Double longueurFacade
    +correspondance(Envie) : Double
  }

  class Maison {
    -Double surfaceHabitable
    -Int nbPieces
    -Int nbEtages
    -String chauffage
    +correspondance(Envie) : Double
  }

  class Appartement {
    -Int nbPieces
    -Int etage
    -Double chargesMensuelles
    +correspondance(Envie) : Double
  }

  Appartement -up-|> BienImmo
  Maison -up-|> BienImmo
  Terrain -up-|> BienImmo

  Maison *-left-"1" Terrain : "terrain"

}

@enduml
